"""empty message

Revision ID: 551e1cda16e2
Revises: 
Create Date: 2018-04-09 20:13:33.900146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551e1cda16e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
