"""empty message

Revision ID: a3c438299e8e
Revises: 551e1cda16e2
Create Date: 2018-04-10 07:41:29.390178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c438299e8e'
down_revision = '551e1cda16e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_User__password', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', '_User__password')
    # ### end Alembic commands ###
